### ISSUE TITLE
Generate a better error when you don't have the right permissions on the org.

### ISSUE THREAD

**Issue by merlijn-sebrechts** [idlab-discover/ghtt#17]
When I try to create milestones on repositories I don't have write access to, I get the following error:

```
Adding milestone 'Deadline lab 4'
Traceback (most recent call last):
  File "/home/merlijn/.local/lib/python3.10/site-packages/ghtt/assignment.py", line 411, in create_issues
    g_repo.create_milestone(
  File "/home/merlijn/.local/lib/python3.10/site-packages/github/Repository.py", line 1350, in create_milestone
    headers, data = self._requester.requestJsonAndCheck(
  File "/home/merlijn/.local/lib/python3.10/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/home/merlijn/.local/lib/python3.10/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/enterprise-server@3.7/rest/reference/issues#create-a-milestone"}
```

This is a super weird error and it took me a long time to figure out what the issue was.

Maybe the tool can check if it has the right permissions before continuing?

**Comment by Michielvk** [comment]
Should be fixed by https://github.com/idlab-discover/ghtt/pull/26.

Issue will be closed once `v1` becomes the new `main` after extensive testing the coming year.
